# default action: build all for TemplateLib and TemplateBin
all:
	cd TemplateLib && make && cd ../TemplateBin && make

#######################################
# clean up
#######################################
clean:
	cd TemplateLib && make clean && cd ../TemplateBin && make clean

